# Homebrew formula for ILMA
# Submit this to homebrew-core or host your own tap:
#   brew tap ilmalang/ilma https://github.com/raihan-js/homebrew-ilma-lang
#   brew install ilma

class Ilma < Formula
  desc "A programming language for children and lifelong learners"
  homepage "https://ilmalang.dev"
  url "https://github.com/raihan-js/ilma-lang/archive/refs/tags/v0.1.0.tar.gz"
  # sha256 — fill this in after publishing v0.1.0:
  # Run: shasum -a 256 ilma-0.1.0.tar.gz
  sha256 "FILL_IN_AFTER_RELEASE"
  license "MIT"
  version "0.1.0"

  bottle do
    # Bottles will be generated by Homebrew CI after submission
  end

  def install
    system "make", "all"
    bin.install "build/ilma"
    (lib/"ilma/runtime").install "src/runtime/ilma_runtime.c"
    (lib/"ilma/runtime").install "src/runtime/ilma_runtime.h"
  end

  def post_install
    ohai "ILMA installed!"
    ohai "Try: echo 'say \"Bismillah\"' > hello.ilma && ilma hello.ilma"
  end

  test do
    (testpath/"hello.ilma").write 'say "Hello from ILMA"'
    assert_match "Hello from ILMA", shell_output("#{bin}/ilma #{testpath}/hello.ilma")
  end
end
