#!/usr/bin/env python3
"""Generate 21 lesson JSON files for website/lessons/"""
import json
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'website', 'lessons')
os.makedirs(OUT, exist_ok=True)

LESSONS = [
  {
    "id": 1,
    "title": "Your First Program",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "say — output to screen",
    "real_world": "What is a computer?",
    "knowledge_note": "The word 'algorithm' comes from Al-Khwarizmi, a 9th-century Muslim mathematician from Baghdad who wrote the first algebra textbook. Every program you write follows his work.",
    "explanation": "The simplest thing ILMA can do is show words on screen. The keyword 'say' does this — like speaking out loud. Write it, then the words in quotes, and your program speaks.",
    "starter_code": 'say "Bismillah"\nsay "Hello, World!"',
    "worked_example": 'say "Bismillah"\nremember name = "Amira"\nsay "Hello, " + name',
    "challenge": "Change the program to say your own name.",
    "hint": 'Change "Amira" to your name inside the quotation marks.',
    "expected_output": "Bismillah\nHello, World!"
  },
  {
    "id": 2,
    "title": "Remembering Things",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "remember — variables",
    "real_world": "What is memory?",
    "knowledge_note": "The brain stores memories so you can use them later. Computers do the same thing with variables — little named boxes that hold values.",
    "explanation": "The keyword 'remember' creates a variable — a named box to store a value. You can then use that name anywhere to get the value back.",
    "starter_code": 'remember name = "Yusuf"\nsay name',
    "worked_example": 'remember name = "Yusuf"\nremember age = 12\nsay name\nsay age',
    "challenge": "Remember your age and say it.",
    "hint": "Use remember age = (your age) then say age.",
    "expected_output": "Yusuf"
  },
  {
    "id": 3,
    "title": "Maths with Code",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "arithmetic — +, -, *, /",
    "real_world": "Why maths matters",
    "knowledge_note": "Zakat is 2.5% of savings above nisab — computers calculate it instantly for millions of people. Maths in code serves the world.",
    "explanation": "ILMA can do maths just like a calculator. Use +, -, *, and / to add, subtract, multiply, and divide. The result appears with say.",
    "starter_code": "say 5 + 3\nsay 10 - 4\nsay 2 * 6",
    "worked_example": "say 5 + 3\nsay 10 - 4\nsay 2 * 6\nsay 100 / 4",
    "challenge": "Calculate 7 * 8.",
    "hint": "Try say 7 * 8 and run it.",
    "expected_output": "8\n6\n12"
  },
  {
    "id": 4,
    "title": "Making Decisions",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "if / otherwise — conditionals",
    "real_world": "Good decisions",
    "knowledge_note": "The Quran says 'think deeply' many times. An if/otherwise block is a computer thinking — it checks a condition and chooses the right path.",
    "explanation": "The keyword 'if' lets your program make decisions. If the condition is true, the first block runs. Otherwise, the second block runs.",
    "starter_code": 'remember age = 10\nif age > 5:\n    say "You can learn to code!"\notherwise:\n    say "Almost ready!"',
    "worked_example": 'remember age = 10\nif age > 5:\n    say "You can learn to code!"\notherwise:\n    say "Almost ready!"',
    "challenge": "Change age to different numbers and see what happens.",
    "hint": "Try age = 3 and age = 15.",
    "expected_output": "You can learn to code!"
  },
  {
    "id": 5,
    "title": "Asking Questions",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "ask — user input",
    "real_world": "Listening is important",
    "knowledge_note": "The Prophet (peace be upon him) was known for listening before speaking. Programs that ask before acting are better programs.",
    "explanation": "The keyword 'ask' pauses your program and waits for the user to type something. The answer is stored in a variable for you to use.",
    "starter_code": 'remember name = ask "What is your name? "\nsay "Assalamu Alaikum, " + name',
    "worked_example": 'remember name = ask "What is your name? "\nsay "Assalamu Alaikum, " + name',
    "challenge": "Ask for someone's favourite colour and say it back.",
    "hint": 'Use remember colour = ask "What is your favourite colour? " then say colour.',
    "expected_output": "Assalamu Alaikum, (your name)"
  },
  {
    "id": 6,
    "title": "Doing Things Again",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "repeat — loops",
    "real_world": "Practice and mastery",
    "knowledge_note": "Repetition is the mother of learning (ancient proverb). Computers repeat millions of times per second — that is their superpower.",
    "explanation": "The keyword 'repeat' runs the indented block a fixed number of times. This lets you do things again and again without writing them over and over.",
    "starter_code": "repeat 3:\n    say \"SubhanAllah\"",
    "worked_example": "repeat 3:\n    say \"SubhanAllah\"",
    "challenge": 'Make it say "Alhamdulillah" 5 times.',
    "hint": 'Change 3 to 5 and "SubhanAllah" to "Alhamdulillah".',
    "expected_output": "SubhanAllah\nSubhanAllah\nSubhanAllah"
  },
  {
    "id": 7,
    "title": "Going Through Everything",
    "tier": "seed",
    "duration_minutes": 10,
    "concept": "for each — iteration",
    "real_world": "Fairness",
    "knowledge_note": "The Quran says each soul will see exactly what it did — nothing missed, nothing added. A for each loop ensures every item is visited.",
    "explanation": "A 'for each' loop goes through every item in a bag one by one. Each time the loop runs, the item variable holds the current item.",
    "starter_code": 'remember fruits = bag["dates", "mango", "apple"]\nfor each fruit in fruits:\n    say fruit',
    "worked_example": 'remember fruits = bag["dates", "mango", "apple"]\nfor each fruit in fruits:\n    say fruit',
    "challenge": "Make your own bag of 3 things and loop through them.",
    "hint": 'Create remember things = bag["...", "...", "..."] with your own items.',
    "expected_output": "dates\nmango\napple"
  },
  {
    "id": 8,
    "title": "Writing Recipes",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "recipe — functions",
    "real_world": "Skills you can share",
    "knowledge_note": "Islamic scholars wrote recipe-like books to share knowledge across centuries. A recipe in ILMA does the same — write it once, share it forever.",
    "explanation": "A 'recipe' is a named block of code you can use over and over. Define it once, then call it by name whenever you need it.",
    "starter_code": 'recipe greet(name):\n    say "Assalamu Alaikum, " + name\n\ngreet("Amira")\ngreet("Yusuf")',
    "worked_example": 'recipe greet(name):\n    say "Assalamu Alaikum, " + name\n\ngreet("Amira")\ngreet("Yusuf")',
    "challenge": 'Write a recipe that says "Bismillah before (action)".',
    "hint": 'recipe bismillah(action): say "Bismillah before " + action',
    "expected_output": "Assalamu Alaikum, Amira\nAssalamu Alaikum, Yusuf"
  },
  {
    "id": 9,
    "title": "Recipes That Answer",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "give back — return values",
    "real_world": "Solving problems",
    "knowledge_note": "Ibn Sina's medical books described treatments that 'returned' results based on inputs. A recipe that gives back does the same.",
    "explanation": "A recipe can compute a value and send it back using 'give back'. The caller receives that value and can use it however they like.",
    "starter_code": "recipe double(n):\n    give back n * 2\n\nsay double(5)\nsay double(21)",
    "worked_example": "recipe double(n):\n    give back n * 2\n\nsay double(5)\nsay double(21)",
    "challenge": "Write a recipe that triples a number.",
    "hint": "recipe triple(n): give back n * 3",
    "expected_output": "10\n42"
  },
  {
    "id": 10,
    "title": "Collections",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "bag — lists",
    "real_world": "Organising things",
    "knowledge_note": "The first libraries were organised collections of knowledge. Bags in ILMA organise data the same way.",
    "explanation": "A 'bag' holds many values in one place. You can loop through them, add items, check sizes, and more.",
    "starter_code": "remember marks = bag[85, 92, 78, 96, 88]\nremember total = 0\nfor each m in marks:\n    total = total + m\nsay \"Total: \" + total",
    "worked_example": "remember marks = bag[85, 92, 78, 96, 88]\nremember total = 0\nfor each m in marks:\n    total = total + m\nsay \"Total: \" + total",
    "challenge": "Find the highest mark (hint: use remember best = 0).",
    "hint": "Inside the loop, check: if m > best: then best = m",
    "expected_output": "Total: 439"
  },
  {
    "id": 11,
    "title": "Labels and Values",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "notebook — key-value store",
    "real_world": "Record keeping",
    "knowledge_note": "Muslim scholars kept detailed records called diwan. A notebook in ILMA is a digital record book — information stored with labels.",
    "explanation": "A 'notebook' stores values with named labels. You can add any information and look it up by its label later.",
    "starter_code": 'remember student = notebook[name: "Amira", age: 12, grade: "A"]\nsay student[name]\nsay student[grade]',
    "worked_example": 'remember student = notebook[name: "Amira", age: 12, grade: "A"]\nsay student[name]\nsay student[grade]',
    "challenge": 'Add a "subject" key and say it.',
    "hint": 'Add subject: "Maths" to the notebook, then say student[subject].',
    "expected_output": "Amira\nA"
  },
  {
    "id": 12,
    "title": "Zakat Calculator",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "use finance — modules",
    "real_world": "Giving back",
    "knowledge_note": "Zakat purifies wealth. 2.5% of savings above nisab goes to those in need. Computing zakat accurately helps millions of Muslims every year.",
    "explanation": "The 'use' keyword imports a module — a collection of built-in recipes. The finance module knows how to calculate zakat, profit, and more.",
    "starter_code": "use finance\nremember savings = 5000\nremember nisab = 595\nremember zakat = finance.zakat(wealth: savings, nisab: nisab)\nsay \"Zakat due: \" + zakat",
    "worked_example": "use finance\nremember savings = 5000\nremember nisab = 595\nremember zakat = finance.zakat(wealth: savings, nisab: nisab)\nsay \"Zakat due: \" + zakat",
    "challenge": "Change the savings amount and recalculate.",
    "hint": "Try savings = 10000 and run again.",
    "expected_output": "Zakat due: 125.0"
  },
  {
    "id": 13,
    "title": "When Things Go Wrong",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "try / when wrong — error handling",
    "real_world": "Resilience",
    "knowledge_note": "Every failure is a lesson. The Quran says 'with hardship comes ease.' Handle errors gracefully and your programs will be stronger.",
    "explanation": "A 'try' block runs code that might fail. If something goes wrong, the 'when wrong' block catches the error and lets you recover gracefully.",
    "starter_code": "try:\n    shout \"test error\"\nwhen wrong:\n    say \"Something went wrong, but I handled it!\"",
    "worked_example": "try:\n    shout \"test error\"\nwhen wrong:\n    say \"Something went wrong, but I handled it!\"",
    "challenge": "Try dividing by zero inside a try block.",
    "hint": "Put say 10 / 0 inside the try block.",
    "expected_output": "Something went wrong, but I handled it!"
  },
  {
    "id": 14,
    "title": "Working with Words",
    "tier": "sapling",
    "duration_minutes": 15,
    "concept": "string operations",
    "real_world": "Language matters",
    "knowledge_note": "Arabic has over 300 words for love alone. Strings let programs work with all of human language — every tongue, every script.",
    "explanation": "Strings have built-in abilities: upper(), lower(), length, contains(), split(), and more. These let you transform and inspect text.",
    "starter_code": 'remember name = "Amira Yusuf"\nsay name.upper()\nsay name.length\nsay name.contains("Yusuf")',
    "worked_example": 'remember name = "Amira Yusuf"\nsay name.upper()\nsay name.length\nsay name.contains("Yusuf")',
    "challenge": "Make the name lowercase and check if it contains your name.",
    "hint": "Use name.lower() and name.contains(\"your name\")",
    "expected_output": "AMIRA YUSUF\n11\nyes"
  },
  {
    "id": 15,
    "title": "Blueprints",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "blueprint — classes",
    "real_world": "Design before you build",
    "knowledge_note": "Every great mosque was planned before it was built. Al-Jazari drew blueprints for machines 800 years ago. A blueprint in ILMA describes what something is and can do.",
    "explanation": "A 'blueprint' defines a type of thing — its data and its abilities. You then create instances from the blueprint, each with their own values.",
    "starter_code": "blueprint Person:\n    create(name, age):\n        me.name = name\n        me.age = age\n    recipe introduce():\n        say \"I am \" + me.name + \", age \" + me.age\n\nremember p = Person(\"Yusuf\", 15)\np.introduce()",
    "worked_example": "blueprint Person:\n    create(name, age):\n        me.name = name\n        me.age = age\n    recipe introduce():\n        say \"I am \" + me.name + \", age \" + me.age\n\nremember p = Person(\"Yusuf\", 15)\np.introduce()",
    "challenge": 'Add a "city" field and mention it in introduce().',
    "hint": "Add me.city = city to create(), then add city to the say line.",
    "expected_output": "I am Yusuf, age 15"
  },
  {
    "id": 16,
    "title": "Standing on Shoulders",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "comes from — inheritance",
    "real_world": "Building on knowledge",
    "knowledge_note": "Every Muslim scholar built on those before them. Ibn Rushd built on Aristotle. You build on their work every time you write 'comes from'.",
    "explanation": "'comes from' lets one blueprint inherit everything from another. You can then add new abilities or change existing ones.",
    "starter_code": 'blueprint Animal:\n    create(name):\n        me.name = name\n    recipe speak():\n        say me.name + " makes a sound"\n\nblueprint Cat comes from Animal:\n    create(name):\n        comes_from.create(name)\n    recipe speak():\n        say me.name + " says: Meow!"\n\nremember c = Cat("Whiskers")\nc.speak()',
    "worked_example": 'blueprint Animal:\n    create(name):\n        me.name = name\n    recipe speak():\n        say me.name + " makes a sound"\n\nblueprint Cat comes from Animal:\n    create(name):\n        comes_from.create(name)\n    recipe speak():\n        say me.name + " says: Meow!"\n\nremember c = Cat("Whiskers")\nc.speak()',
    "challenge": 'Create a Dog blueprint that says "Woof!"',
    "hint": 'Copy the Cat blueprint and change the name and "Meow!" to "Woof!"',
    "expected_output": "Whiskers says: Meow!"
  },
  {
    "id": 17,
    "title": "Evidence-Based Decisions",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "check / when — pattern matching",
    "real_world": "Evidence-based decisions",
    "knowledge_note": "Islamic jurisprudence (fiqh) uses evidence to reach rulings — check the evidence, decide accordingly. Pattern matching in code does the same.",
    "explanation": "A 'check' block tests a value against many patterns. The first matching 'when' block runs. 'otherwise' handles anything not matched.",
    "starter_code": "remember score = 87\ncheck score:\n    when 90..100:\n        say \"Excellent — A\"\n    when 80..89:\n        say \"Good — B\"\n    when 70..79:\n        say \"Passing — C\"\n    otherwise:\n        say \"Keep trying\"",
    "worked_example": "remember score = 87\ncheck score:\n    when 90..100:\n        say \"Excellent — A\"\n    when 80..89:\n        say \"Good — B\"\n    when 70..79:\n        say \"Passing — C\"\n    otherwise:\n        say \"Keep trying\"",
    "challenge": "Change the score and see the result change.",
    "hint": "Try score = 95, score = 72, score = 55.",
    "expected_output": "Good — B"
  },
  {
    "id": 18,
    "title": "Recipes as Values",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "lambdas — first-class functions",
    "real_world": "Functions are first class",
    "knowledge_note": "In mathematics, functions can take other functions as input. Al-Khwarizmi used this concept in algebra 1200 years ago.",
    "explanation": "In ILMA, a recipe can be stored in a variable and passed around. A short recipe with no name is called a lambda.",
    "starter_code": "remember double = recipe(n): give back n * 2\nremember nums = bag[1, 2, 3, 4, 5]\nremember doubled = nums.map(double)\nfor each n in doubled:\n    say n",
    "worked_example": "remember double = recipe(n): give back n * 2\nremember nums = bag[1, 2, 3, 4, 5]\nremember doubled = nums.map(double)\nfor each n in doubled:\n    say n",
    "challenge": "Write a triple lambda and map it over the same bag.",
    "hint": "remember triple = recipe(n): give back n * 3",
    "expected_output": "2\n4\n6\n8\n10"
  },
  {
    "id": 19,
    "title": "Science with Code",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "use science — science module",
    "real_world": "Physics is everywhere",
    "knowledge_note": "Ibn al-Haytham (Alhazen) invented the scientific method 1000 years ago. Science and Islam walk together — curiosity about the universe is an act of worship.",
    "explanation": "The science module gives you physics formulas as ready-made recipes. Gravity, speed, energy, temperature — all built in.",
    "starter_code": "use science\nremember mass = 70\nremember force = science.gravity(mass)\nsay \"Gravity force: \" + force + \" N\"\nsay science.celsius_to_fahrenheit(100)",
    "worked_example": "use science\nremember mass = 70\nremember force = science.gravity(mass)\nsay \"Gravity force: \" + force + \" N\"\nsay science.celsius_to_fahrenheit(100)",
    "challenge": "Calculate the gravity force for your own weight.",
    "hint": "Change mass = 70 to your weight in kg.",
    "expected_output": "Gravity force: 686.0 N\n212.0"
  },
  {
    "id": 20,
    "title": "Testing Your Code",
    "tier": "tree",
    "duration_minutes": 20,
    "concept": "ilma test — automated tests",
    "real_world": "Quality matters",
    "knowledge_note": "Muslim engineers tested their machines before use. A program without tests is a bridge without inspection — you never know when it will fail.",
    "explanation": "A 'test' block checks that your code does exactly what you expect. Run tests to catch mistakes before your users do.",
    "starter_code": "test \"doubling works\":\n    remember result = 2 * 21\n    check result is 42\n\ntest \"strings work\":\n    remember s = \"hello\"\n    check s.upper() is \"HELLO\"",
    "worked_example": "test \"doubling works\":\n    remember result = 2 * 21\n    check result is 42\n\ntest \"strings work\":\n    remember s = \"hello\"\n    check s.upper() is \"HELLO\"",
    "challenge": "Write a test for a recipe you created.",
    "hint": "Write a recipe, then write test \"my recipe works\": and check its output.",
    "expected_output": "All tests passed!"
  },
  {
    "id": 21,
    "title": "Build Something Real",
    "tier": "tree",
    "duration_minutes": 30,
    "concept": "capstone — full program",
    "real_world": "Your gift to the world",
    "knowledge_note": "The greatest scholars completed their work and shared it. Ibn Sina's Canon of Medicine took decades. Your program, completed and working, is your gift to the world.",
    "explanation": "Now bring everything together — blueprints, bags, loops, recipes, and modules — to build a complete program.",
    "starter_code": "use finance\n\nblueprint Student:\n    create(name):\n        me.name = name\n        me.grades = bag[]\n    recipe add_grade(score):\n        me.grades.add(score)\n    recipe average():\n        if me.grades.size is 0:\n            give back 0\n        remember total = 0\n        for each g in me.grades:\n            total = total + g\n        give back total / me.grades.size\n    recipe report():\n        say me.name + \" — average: \" + me.average()\n\nremember s = Student(\"Amira\")\ns.add_grade(92)\ns.add_grade(85)\ns.add_grade(97)\ns.report()",
    "worked_example": "use finance\n\nblueprint Student:\n    create(name):\n        me.name = name\n        me.grades = bag[]\n    recipe add_grade(score):\n        me.grades.add(score)\n    recipe average():\n        if me.grades.size is 0:\n            give back 0\n        remember total = 0\n        for each g in me.grades:\n            total = total + g\n        give back total / me.grades.size\n    recipe report():\n        say me.name + \" — average: \" + me.average()\n\nremember s = Student(\"Amira\")\ns.add_grade(92)\ns.add_grade(85)\ns.add_grade(97)\ns.report()",
    "challenge": "Add yourself as a student with your own grades.",
    "hint": "Create remember me = Student(\"(your name)\") and call add_grade() a few times.",
    "expected_output": "Amira — average: 91.33333333333333"
  }
]

for lesson in LESSONS:
    filename = os.path.join(OUT, f"{lesson['id']:02d}_{lesson['title'].lower().replace(' ', '_').replace('/', '_')}.json")
    with open(filename, 'w') as f:
        json.dump(lesson, f, indent=2, ensure_ascii=False)
    print(f"  Written: {os.path.basename(filename)}")

print(f"\nTotal: {len(LESSONS)} lessons written to {OUT}/")
